### ISSUE TITLE
collections folder

### ISSUE THREAD

**Issue by esepro** [CrimsonSunrise/Glimpse#2]
I'm having problem on step 5 to import the base data into every collection
I can't find the collections folder my database folder is in C drive data\db in windows10 
and i can't find them in the glimpse project folder too

I'm looking to autotrade using strike rate and expiry can you give an example how i can acheive it

**Comment by CrimsonSunrise** [comment]
I'm sorry for taking so long, didn't receive any notifications about github and was busy on other projects.
To import all the collections easilly, you can install MongoDB Compass to have a better visualization.

**Comment by esepro** [comment]
I've already installed MongoDB Compass and created Glimpse Database with all the collections mentioned in step 4 
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/108810896/179957881-ac83d866-062c-4beb-b45a-5da27fc8bb47.png">


but when I click on import data I can't find the collections folder what base data should I import inside the collections  
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/108810896/179957934-5c9ecca2-8309-4d5c-a2d9-c868bc91131e.png">

**Comment by CrimsonSunrise** [comment]
Oh, I see.
My apologies. I forgot to upload the collections folder into the project.
Now is everything there.

Any questions, feel free to ask.

**Comment by esepro** [comment]
thanks I've added all the base data and edited the  IP Address where name is equal to apiAddress but couldn't find the document   where name is equal to analysisAccount or should I edit the Accounts collection where name, email and password are empty

**Comment by esepro** [comment]
I've added the new document with name equal to analysisAccount and value equal to email/password 
and the database is updating with new candles but I could only see open and close how to get high, low and volume 
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/108810896/179991509-8280b608-bfc0-4818-9bd2-e1abb8db2656.png">

and it seems there is limit for candles data only 15 candles data is available how can I get data for 200 candles 

I've started the ionic app too but I can't login with default values as admin it keeps loading
should I edit any document in the database for email and password?
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/108810896/179991791-237e732e-879f-47f7-a740-32eb85cca406.png">

**Comment by CrimsonSunrise** [comment]
The parameters for the candles lenghts and attributes to save into the database are located in the actives scripts inside /auxiliar/candles folder.

On the line 22 you can set the lenght, default is 15.
On the line 41 you can add more attributes based on the query result from the broker.

About the loading screen, check your console to see if its there any error. It should be something with the API connection .

**Comment by esepro** [comment]
I got error on line 41 when I added more attributes
<img width="1440" alt="5" src="https://user-images.githubusercontent.com/108810896/179997428-cea5f451-533a-41ab-a609-d9429d940044.png">

and for login there is no error in console what is the default email and password I just used admin for both
<img width="1440" alt="6" src="https://user-images.githubusercontent.com/108810896/179997781-941ee1f5-0fc7-4996-a763-cf2a3f09d158.png">

**Comment by CrimsonSunrise** [comment]
You have to use the keys that you get from the broker's candles stream.
When querying the candles, there's no "high" or "low" key, instead Iq Option uses "max" and "min".
I've edited the readme page and included the [IQ Option API documentation](https://iqoptionapi.github.io/iqoptionapi/en/) if you want to check how it works and what to expect from the queries.

To keep this session organized I will close this issue and you can open another one if you have doubts about another subject other than the collections folder.
