### ISSUE TITLE
app login

### ISSUE THREAD

**Issue by esepro** [CrimsonSunrise/Glimpse#3]
What is the default email and password I used admin for both but can't login into the app

**Comment by CrimsonSunrise** [comment]
In the "Account" collection on your database you can set the "email" and "password" values.
You can check what is showing on your browser's console for more information about errors.

**Comment by esepro** [comment]
I've set both email and password to admin but the page is just loading 
with console showing true and timeout error I think the post request is not going to localhost
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/108810896/180012290-0317dbf7-2279-41d3-ac60-f82180c62728.png">

**Comment by esepro** [comment]
It seems the ip address in connection.js file line 6 is hardcoded I've edited the address and it works fine now

**Comment by CrimsonSunrise** [comment]
Great! I was about to point that.
I'll describe on the documentation where to find and how to change.
